### ISSUE TITLE
Request: Notifications should work via ntfy.sh, not just google

### ISSUE THREAD

**Issue by cobordism** [gobitfly/eth2-beaconchain-explorer-app#231]
**Describe the bug**
Notificationa cannot be enabled on a google free android. It seems "google play services" is hard coded as the only mechanism.

**To Reproduce**
1. Install app on a google free android
2. try to enable notifications

**Expected behavior**
It would be great if you could choose whatever notification service yoi feel most comfortable with, including self hosted options. See ntfy.sh for examples.

Apps that support ntfy include fedilab/mastodon, and element/matrix for example.

**Phone (please complete the following information):**
 - OS: Graphene OS  and /e/ both do not work. Any degoogled android will have this issue.

**Additional context**
Please don't feed google any more data.

**Comment by manuelsc** [comment]
Can you please elaborate what the actual bug is you are experiencing, you can not change your notification settings?

At the moment, we do not support other in app push notification providers. But you should be able to set notification settings in the google free version and see an info banner about our webhook support when opening the notification settings. You can configure webhook notifications by following this link in the app or directly on the website here https://beaconcha.in/user/webhooks. From there you can configure notifications via discord, telegram or any custom solutions.

**Comment by cobordism** [comment]
![Screenshot_20230726-164917](https://github.com/gobitfly/eth2-beaconchain-explorer-app/assets/12838530/ce1f9b8a-842e-4097-994a-de8fa204b17f)

The moment I try to toggle notifications, I get this message.

I simply though I should be able to select a notification service (like ntfy.sh) other than google right there in the app under "notifications".

I had not looked into webhooks.

**Comment by manuelsc** [comment]
@cobordism We changed the behavior in App version 4.5.0 to allow you to change the toggle. We added an info dialog that you will not receive push notifications if play services are missing but you can configure webhook notifications as mentioned above on the website. You should now be able to control your notification preferences in the app if you have set up webhook notifications.

Currently we have no plans to support other means of push notification services which is why I'll now close this issue. Please use our webhook notification system instead :)
